export enum ActionTypeEnum {
  'Login' = 1,
  'Logout' = 2,
  'SessionEnd' = 3,
  'Activate' = 4,
  'CreatePlano' = 5,
  'SubmitPlano' = 6,
  'ApprovePlano' = 7,
  'EditPlano' = 8,
  'CreateOrder' = 9,
  'EditOrder' = 10,
  'SubmitOrder' = 11,
  'ApproveOrder' = 12,
  'DeletePlano' = 13,
  'CopyPlano' = 14,
  'ValidatePlano' = 15,
  'UnValidatePlano' = 16,
}
