export const widgetService = {
  getProductsData() {
    return [
      {
        id: '1000',
        code: 'f230fh0g3',
        name: 'PORTUGAL 2300',
        description: 'Description',
        image: 'bamboo-watch.jpg',
        skus: 65,
        category: 'Accessories',
        quantity: 24,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1001',
        code: 'nvklal433',
        name: 'GERMANY 2345',
        description: 'Description',
        image: 'black-watch.jpg',
        skus: 72,
        category: 'Wall',
        quantity: 61,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1002',
        code: 'zz21cz3c1',
        name: 'GERMANY 2300',
        description: 'Description',
        image: 'blue-band.jpg',
        skus: 79,
        category: 'Fitness',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
      },
      {
        id: '1003',
        code: '244wgerg2',
        name: 'GREECE 2300',
        description: 'Description',
        image: 'blue-t-shirt.jpg',
        skus: 29,
        category: 'Clothing',
        quantity: 25,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1004',
        code: 'h456wer53',
        name: 'GREECE 2345',
        description: 'Product Description',
        image: 'bracelet.jpg',
        skus: 15,
        category: 'Accessories',
        quantity: 73,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1005',
        code: 'av2231fwg',
        name: 'UK 600',
        description: 'Description',
        image: 'brown-purse.jpg',
        skus: 120,
        category: 'Accessories',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 4,
      },
      {
        id: '1006',
        code: 'bib36pfvm',
        name: 'UK 1400',
        description: 'Description',
        image: 'chakra-bracelet.jpg',
        skus: 32,
        category: 'Accessories',
        quantity: 5,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
      },
      {
        id: '1007',
        code: 'mbvjkgip5',
        name: 'UK 1530',
        description: 'Description',
        image: 'galaxy-earrings.jpg',
        skus: 34,
        category: 'Accessories',
        quantity: 23,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1008',
        code: 'vbb124btr',
        name: 'FRANCE 2300',
        description: 'Description',
        image: 'game-controller.jpg',
        skus: 99,
        category: 'Electronics',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        rating: 4,
      },
      {
        id: '1009',
        code: 'cm230f032',
        name: 'FRANCE 2345',
        description: 'Description',
        image: 'gaming-set.jpg',
        skus: 299,
        category: 'Electronics',
        quantity: 63,
        inventoryStatus: 'INSTOCK',
        rating: 3,
      },
      {
        id: '1010',
        code: 'plb34234v',
        name: 'FRANCE 1200',
        description: 'Description',
        image: 'gold-phone-case.jpg',
        skus: 24,
        category: 'Accessories',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 4,
      },
      {
        id: '1011',
        code: '4920nnc2d',
        name: 'SPAIN 2300',
        description: 'Description',
        image: 'green-earbuds.jpg',
        skus: 89,
        category: 'Electronics',
        quantity: 23,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1012',
        code: '250vm23cc',
        name: 'SPAIN 7400',
        description: 'Description',
        image: 'green-t-shirt.jpg',
        skus: 49,
        category: 'Clothing',
        quantity: 74,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1013',
        code: 'fldsmn31b',
        name: 'SPAIN 600',
        description: 'Description',
        image: 'grey-t-shirt.jpg',
        skus: 48,
        category: 'Clothing',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 3,
      },
      {
        id: '1014',
        code: 'waas1x2as',
        name: 'SPAIN 1400',
        description: 'Description',
        image: 'headphones.jpg',
        skus: 175,
        category: 'Electronics',
        quantity: 8,
        inventoryStatus: 'LOWSTOCK',
        rating: 5,
      },
      {
        id: '1015',
        code: 'vb34btbg5',
        name: 'ITALY 400',
        description: 'Description',
        image: 'light-green-t-shirt.jpg',
        skus: 49,
        category: 'Clothing',
        quantity: 34,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1016',
        code: 'k8l6j58jl',
        name: 'ITALY 1500',
        description: 'Description',
        image: 'lime-band.jpg',
        skus: 79,
        category: 'Fitness',
        quantity: 12,
        inventoryStatus: 'INSTOCK',
        rating: 3,
      },
      {
        id: '1017',
        code: 'v435nn85n',
        name: 'POLAND 1600',
        description: 'Description',
        image: 'mini-speakers.jpg',
        skus: 85,
        category: 'Clothing',
        quantity: 42,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1018',
        code: '09zx9c0zc',
        name: 'POLAND 2300',
        description: 'Description',
        image: 'painted-phone-case.jpg',
        skus: 56,
        category: 'Accessories',
        quantity: 41,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1019',
        code: 'mnb5mb2m5',
        name: 'POLAND 1600',
        description: 'Description',
        image: 'pink-band.jpg',
        skus: 79,
        category: 'Fitness',
        quantity: 63,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1020',
        code: 'r23fwf2w3',
        name: 'SWEDEN 2300',
        description: 'Description',
        image: 'pink-purse.jpg',
        skus: 110,
        category: 'Accessories',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 4,
      },
      {
        id: '1021',
        code: 'pxpzczo23',
        name: 'SWEDEN 1600',
        description: 'Description',
        image: 'purple-band.jpg',
        skus: 79,
        category: 'Fitness',
        quantity: 6,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
      },
      {
        id: '1022',
        code: '2c42cb5cb',
        name: 'SWEDEN 1800',
        description: 'Description',
        image: 'purple-gemstone-necklace.jpg',
        skus: 45,
        category: 'Accessories',
        quantity: 62,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1023',
        code: '5k43kkk23',
        name: 'NORWAY 2300',
        description: 'Description',
        image: 'purple-t-shirt.jpg',
        skus: 49,
        category: 'Clothing',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        rating: 5,
      },
      {
        id: '1024',
        code: 'lm2tny2k4',
        name: 'NORWAY 2400',
        description: 'Description',
        image: 'shoes.jpg',
        skus: 64,
        category: 'Clothing',
        quantity: 0,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1025',
        code: 'nbm5mv45n',
        name: 'NORWAY 600',
        description: 'Description',
        image: 'sneakers.jpg',
        skus: 78,
        category: 'Clothing',
        quantity: 52,
        inventoryStatus: 'INSTOCK',
        rating: 4,
      },
      {
        id: '1026',
        code: 'zx23zc42c',
        name: 'NORWAY 1600',
        description: 'Description',
        image: 'teal-t-shirt.jpg',
        skus: 49,
        category: 'Clothing',
        quantity: 3,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
      },
      {
        id: '1027',
        code: 'acvx872gc',
        name: 'FRANCE 800',
        description: 'Description',
        image: 'yellow-earbuds.jpg',
        skus: 89,
        category: 'Electronics',
        quantity: 35,
        inventoryStatus: 'INSTOCK',
        rating: 3,
      },
      {
        id: '1028',
        code: 'tx125ck42',
        name: 'FRANCE 1000',
        description: 'Description',
        image: 'yoga-mat.jpg',
        skus: 20,
        category: 'Fitness',
        quantity: 15,
        inventoryStatus: 'INSTOCK',
        rating: 5,
      },
      {
        id: '1029',
        code: 'gwuby345v',
        name: 'FRANCE 1100',
        description: 'Description',
        image: 'yoga-set.jpg',
        skus: 20,
        category: 'Fitness',
        quantity: 25,
        inventoryStatus: 'INSTOCK',
        rating: 8,
      },
    ]
  },
  getProductsSmall() {
    return Promise.resolve(this.getProductsData().slice(0, 10))
  },
}
