@PM-AdminApp.Server_HostAddress = https://localhost:7134
@PM_AdminApp.Server_HostAddress = http://localhost:5151

GET {{PM_AdminApp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{PM-AdminApp.Server_HostAddress}}/api/brands/GetBrands

###
